import AdminLayout from '@/Layouts/AdminLayout';
import { Head, router, useForm, usePage } from '@inertiajs/react';
import { useMemo, useState } from 'react';

const labels = { not_started: 'Não iniciado', draft: 'Rascunho', completed: 'Voto concluído' };
const styles = { not_started: 'bg-slate-100 text-slate-700 ring-slate-200', draft: 'bg-sky-50 text-sky-700 ring-sky-200', completed: 'bg-emerald-50 text-emerald-700 ring-emerald-200' };

export default function JudgeIndex({ judges, votingOpen }) {
    const { flash } = usePage().props;
    const [showForm, setShowForm] = useState(false);
    const [query, setQuery] = useState('');
    const [status, setStatus] = useState('all');
    const form = useForm({ name: '', email: '' });
    const visible = useMemo(() => judges.filter((judge) => (status === 'all' || judge.vote_status === status) && `${judge.name} ${judge.email} ${judge.credential}`.toLowerCase().includes(query.toLowerCase())), [judges, query, status]);
    const submit = (event) => { event.preventDefault(); form.post(route('admin.judges.store'), { preserveScroll: true, onSuccess: () => { form.reset(); setShowForm(false); } }); };
    const toggleVoting = () => router.patch(route('admin.judges.toggle-voting'), {}, { preserveScroll: true });

    return <AdminLayout title="Gerenciamento de juízes" description="Cadastre os avaliadores e controle o período de votação estética."><Head title="Gerenciamento de juízes" />
        <div className={`mb-6 inline-flex items-center gap-2 rounded-full px-4 py-2 text-sm font-bold ring-1 ${votingOpen ? 'bg-emerald-50 text-emerald-700 ring-emerald-200' : 'bg-slate-100 text-slate-600 ring-slate-200'}`}><i className={`size-2 rounded-full ${votingOpen ? 'bg-emerald-600' : 'bg-slate-400'}`} />Janela {votingOpen ? 'aberta' : 'fechada'}</div>
        <section className="grid gap-5 lg:grid-cols-2">
            <article className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-100"><h2 className="text-lg font-bold">Cadastro de juiz</h2><p className="mt-1 text-sm text-slate-500">Gere credenciais únicas para os avaliadores externos.</p><button type="button" onClick={() => setShowForm((value) => !value)} className="mt-5 h-11 rounded-lg bg-sky-700 px-5 text-sm font-bold text-white hover:bg-sky-800">+ Cadastrar juiz</button>{showForm && <form onSubmit={submit} className="mt-5 grid gap-3 border-t border-slate-100 pt-5"><Field label="Nome" error={form.errors.name}><input value={form.data.name} onChange={(e) => form.setData('name', e.target.value)} /></Field><Field label="E-mail" error={form.errors.email}><input type="email" value={form.data.email} onChange={(e) => form.setData('email', e.target.value)} /></Field><div className="flex gap-3"><button disabled={form.processing} className="h-10 rounded-lg bg-[#172938] px-4 text-sm font-bold text-white disabled:opacity-50">Salvar juiz</button><button type="button" onClick={() => setShowForm(false)} className="text-sm font-semibold text-slate-600">Cancelar</button></div></form>}</article>
            <article className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-100"><h2 className="text-lg font-bold">Janela de votação</h2><p className="mt-1 text-sm text-slate-500">{votingOpen ? 'Os juízes podem registrar ou concluir seus votos.' : 'A votação estética está bloqueada para os juízes.'}</p><button type="button" onClick={toggleVoting} className={`mt-5 h-11 rounded-lg px-5 text-sm font-bold text-white ${votingOpen ? 'bg-rose-700 hover:bg-rose-800' : 'bg-orange-500 hover:bg-orange-600'}`}>{votingOpen ? 'Encerrar janela de votação' : 'Iniciar janela de votação'}</button></article>
        </section>
        {flash?.success && <p className="mt-6 rounded-lg bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-800">{flash.success}</p>}
        <section className="mt-6 rounded-2xl border border-slate-100 bg-white p-5 shadow-sm sm:p-7"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="text-xl font-bold">Juízes cadastrados</h2><p className="mt-0.5 text-sm text-slate-500">{judges.length} avaliadores registrados.</p></div><div className="flex flex-col gap-3 sm:flex-row"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="⌕  Buscar juiz" className="h-10 rounded-lg border-slate-200 text-sm shadow-sm focus:border-sky-600 focus:ring-sky-600 sm:w-56" /><select value={status} onChange={(event) => setStatus(event.target.value)} className="h-10 rounded-lg border-slate-200 text-sm font-semibold text-slate-700 shadow-sm"><option value="all">Todos os status</option>{Object.entries(labels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div></div><div className="mt-6 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50 text-xs font-bold uppercase tracking-wide text-slate-500"><tr><th className="rounded-l-md px-4 py-3">Nome</th><th className="px-4 py-3">E-mail</th><th className="px-4 py-3">Credencial</th><th className="rounded-r-md px-4 py-3">Status do voto</th></tr></thead><tbody className="divide-y divide-slate-200">{visible.map((judge) => <tr key={judge.id} className="hover:bg-slate-50/70"><td className="px-4 py-4 font-semibold">{judge.name}</td><td className="px-4 py-4">{judge.email}</td><td className="px-4 py-4 font-mono text-xs text-slate-600">{judge.credential}</td><td className="px-4 py-4"><span className={`inline-flex rounded-full px-3 py-1 text-xs font-semibold ring-1 ${styles[judge.vote_status]}`}>{labels[judge.vote_status]}</span></td></tr>)}</tbody></table>{!visible.length && <p className="py-12 text-center text-sm text-slate-500">Nenhum juiz encontrado.</p>}</div></section>
    </AdminLayout>;
}

function Field({ label, error, children }) { return <label className="text-sm font-semibold">{label}<span className="mt-1.5 block">{children}</span>{error && <small className="mt-1 block text-rose-600">{error}</small>}</label>; }
